<?php
 $pageTitle='Bob Green Memorial Trophy (All-in Cup)';
 include ('pageheader.php');
?>
<h3>Bob Green Memorial Trophy (All-in Cup)</h3><br>
<p class="center"><br><b>Draw to be advised after games in week 3<br>60 teams below have elected to take part in the competition<br>Teams must win the fixture played in week 3 in order to be entered into the 2nd round draw</b><br><br></p>
<table class="border">
<tr><td class="normal">Artists (P)</td></tr>
<tr><td class="normal">Avengers (P)</td></tr>
<tr><td class="normal">Better Half (P)</td></tr>
<tr><td class="normal">Bridgetown (P)</td></tr>
<tr><td class="normal">Jack High (P)</td></tr>
<tr><td class="normal">Moscow Dynamos (P)</td></tr>
<tr><td class="normal">Old Muckers (P)</td></tr>
<tr><td class="normal">Persuaders (P)</td></tr>
<tr><td class="normal">Ratepayers (P)</td></tr>
<tr><td class="normal">Rebels (P)</td></tr>
<tr><td class="normal">Tadgers (P)</td></tr>
<tr><td class="normal">Tearaways (P)</td></tr>
<tr><td class="normal">Tomtits (P)</td></tr>
<tr><td class="normal">Village Idiots (P)</td></tr>
<tr><td class="normal">BA Rangers (1)</td></tr>
<tr><td class="normal">Boars Head (1)</td></tr>
<tr><td class="normal">Duke of Beaufort (1)</td></tr>
<tr><td class="normal">Fusiliers (1)</td></tr>
<tr><td class="normal">Loungers (1)</td></tr>
<tr><td class="normal">Lynch Pins (1)</td></tr>
<tr><td class="normal">Morse Codes (1)</td></tr>
<tr><td class="normal">Nobblers (1)</td></tr>
<tr><td class="normal">Wanderers (1)</td></tr>
<tr><td class="normal">Birdies (2)</td></tr>
<tr><td class="normal">Dirty Turkeys (2)</td></tr>
<tr><td class="normal">Dropouts (2)</td></tr>
<tr><td class="normal">Lurkos (2)</td></tr>
<tr><td class="normal">Millermen (2)</td></tr>
<tr><td class="normal">Misfits (2)</td></tr>
<tr><td class="normal">Riff Raff (2)</td></tr>
<tr><td class="normal">Wurzels (2)</td></tr>
<tr><td class="normal">X-Rs (2)</td></tr>
<tr><td class="normal">Allsorts (3)</td></tr>
<tr><td class="normal">Cam A (3)</td></tr>
<tr><td class="normal">Elites (3)</td></tr>
<tr><td class="normal">Happy Shambles (3)</td></tr>
<tr><td class="normal">Oddbods (3)</td></tr>
<tr><td class="normal">Quality Factors (3)</td></tr>
<tr><td class="normal">Surgical Spirits (3)</td></tr>
<tr><td class="normal">Tipsy Moonshiners (3)</td></tr>
<tr><td class="normal">Wannabees (3)</td></tr>
<tr><td class="normal">Duty Free (4)</td></tr>
<tr><td class="normal">Fizz Kids (4)</td></tr>
<tr><td class="normal">Guys and Dolls (4)</td></tr>
<tr><td class="normal">Not a Clue (4)</td></tr>
<tr><td class="normal">Pheasant Pluckers (4)</td></tr>
<tr><td class="normal">Slimbridge LSC (4)</td></tr>
<tr><td class="normal">Warriors (4)</td></tr>
<tr><td class="normal">Bangers (5)</td></tr>
<tr><td class="normal">Chaos (5)</td></tr>
<tr><td class="normal">Hopefuls (5)</td></tr>
<tr><td class="normal">Jolly Mariners (5)</td></tr>
<tr><td class="normal">Rogues (5)</td></tr>
<tr><td class="normal">Titbits (5)</td></tr>
<tr><td class="normal">Fielders (6)</td></tr>
<tr><td class="normal">Ladybirds (6)</td></tr>
<tr><td class="normal">Lobitanhope (6)</td></tr>
<tr><td class="normal">Rockhampton Rams (6)</td></tr>
<tr><td class="normal">Sharpness Playmates (6)</td></tr>
<tr><td class="normal">Super Troopers (6)</td></tr>
</table>
<?php include ('pagefooter.php');?>
