<?php
 echo "<table width=\"100%\">\n";
 echo " <tr><td class=\"hdrsmall\" colspan=\"2\">Downloads</td></tr>\n";
  echo " <tr><td class=\"normalcenter\"><a href=\"downloads/Scoresheet.pdf\" title=\"&raquo; download Blank Scoresheet\" target=\"_blank\"><img src=\"resource/pdf.gif\" border=\"0\" alt=\"&raquo; download Blank Scoresheet\"></a></td><td class=\"normal\"><a href=\"downloads/Scoresheet.pdf\" title=\"&raquo; download Blank Scoresheet\" target=\"_blank\">Blank Scoresheet</a></td></tr>\n";
  echo " <tr><td class=\"normalcenter\"><a href=\"downloads/AGM_Minutes_2014.pdf\" title=\"&raquo; download Minutes from AGM on 11/6/2014\" target=\"_blank\"><img src=\"resource/pdf.gif\" border=\"0\" alt=\"&raquo; download Minutes from AGM on 11/6/2014\"></a></td><td class=\"normal\"><a href=\"downloads/AGM_Minutes_2014.pdf\" title=\"&raquo; download Minutes from AGM on 11/6/2014\" target=\"_blank\">Minutes from AGM on 11/6/2014</a></td></tr>\n";
  echo " <tr><td class=\"normalcenter\"><a href=\"downloads/AGM_Registration_2015-16.pdf\" title=\"&raquo; download AGM / Team Registration 2015/16\" target=\"_blank\"><img src=\"resource/pdf.gif\" border=\"0\" alt=\"&raquo; download AGM / Team Registration 2015/16\"></a></td><td class=\"normal\"><a href=\"downloads/AGM_Registration_2015-16.pdf\" title=\"&raquo; download AGM / Team Registration 2015/16\" target=\"_blank\">AGM / Team Registration 2015/16</a></td></tr>\n";
  echo " <tr><td class=\"normalcenter\"><a href=\"downloads/BDSL_Rules.pdf\" title=\"&raquo; download League Rules 2015/16\" target=\"_blank\"><img src=\"resource/pdf.gif\" border=\"0\" alt=\"&raquo; download League Rules 2015/16\"></a></td><td class=\"normal\"><a href=\"downloads/BDSL_Rules.pdf\" title=\"&raquo; download League Rules 2015/16\" target=\"_blank\">League Rules 2015/16</a></td></tr>\n";
  echo " <tr><td class=\"normalcenter\"><a href=\"downloads/Charity_Scheme_2015-16.pdf\" title=\"&raquo; download Charity Collection Scheme 2015/16\" target=\"_blank\"><img src=\"resource/pdf.gif\" border=\"0\" alt=\"&raquo; download Charity Collection Scheme 2015/16\"></a></td><td class=\"normal\"><a href=\"downloads/Charity_Scheme_2015-16.pdf\" title=\"&raquo; download Charity Collection Scheme 2015/16\" target=\"_blank\">Charity Collection Scheme 2015/16</a></td></tr>\n";
  echo " <tr><td class=\"normalcenter\"><a href=\"downloads/AGM_Minutes_2015.pdf\" title=\"&raquo; download Minutes from AGM on 10/6/2015\" target=\"_blank\"><img src=\"resource/pdf.gif\" border=\"0\" alt=\"&raquo; download Minutes from AGM on 10/6/2015\"></a></td><td class=\"normal\"><a href=\"downloads/AGM_Minutes_2015.pdf\" title=\"&raquo; download Minutes from AGM on 10/6/2015\" target=\"_blank\">Minutes from AGM on 10/6/2015</a></td></tr>\n";
 echo "</table>\n";
?>
